FORMATTING = {
  titleLeft: { color: "E6DDC9", float: :left, fontsize: 26 },
  titleRight: { color: "E6DDC9", float: :right, fontsize: 26, translate: [0, 5], scale: 0.8, margintop: -5 },
  scaleAD: { color: "EB8D34" },
  spellActive: { color: "F0E6D2" },
  spellPassive: { color: "F0E6D2" },
  mainText: { color: "A09B8C", display: 0 },
  subtitleLeft: { color: "F0E6D2", float: :left, clear: :right, paddingleft: 1, margintop: -5 },
  subtitleRight: { color: "A09B8C", float: :right, clear: :right, margintop: -5 },
  postScriptTitle: { color: "A09B8C", display: 0 },
  postScriptLeft: { color: "A09B8C", float: :left, },
  postScriptRight: { color: "A09B8C", float: :right, display: 0, textalign: :right },
  keywordStealth: { color: "D182BE" },
  stealth: { color: "D182BE" },
  scaleAP: { color: "786CFF" },
  scaleSize: { color: "67D67C" },
  consumable: { color: "F0E6D2" },
  gold: { color: "D8AE4B" },
  passive: { color: "F0E6D2" },
  unique: { color: "F0E6D2" },
  rules: { color: "5A5955", italic: true },
  rule: { color: "5A5955", italic: true },
  active: { color: "FFB218" },
  scaleMana: { color: "189CE7" },
  scaleHealth: { color: "1F995C" },
  health: { color: "1F995C" },
  infoArea: { color: "A09B8C" },
  scaleLevel: { color: "F0E6D2" },
  scaleAbilityHaste: {color: "AAFAD2" },
  scaleAF: { color: "8155DE" },
  crit: { color: "FACDAF" },
  if0is0: { color: "5A5955" },
  if0is1: { color: "5A5955" },
  if2is1: { color: "5A5955" },
  if3is1: { color: "5A5955" },
  if4is1: { color: "5A5955" },
  if0is2: { color: "5A5955" },
  if1is2: { color: "5A5955" },
  if3is2: { color: "5A5955" },
  if4is2: { color: "5A5955" },
  if0is3: { color: "5A5955" },
  if1is3: { color: "5A5955" },
  if2is3: { color: "5A5955" },
  if4is3: { color: "5A5955" },
  if0is4: { color: "5A5955" },
  if1is4: { color: "5A5955" },
  if2is4: { color: "5A5955" },
  if3is4: { color: "5A5955" },
  if1is1: { color: "F0E6D2" },
  is2is2: { color: "F0E6D2" },
  if3is3: { color: "F0E6D2" },
  if4is4: { color: "F0E6D2" },
  if0isnot0: { color: "5A5955" },
  if1isnot0: { color: "F0E6D2" },
  if2isnot0: { color: "F0E6D2" },
  if3isnot0: { color: "F0E6D2" },
  kaisaLWActive0: { color: "5A5955" },
  kaisaLWActive1: { color: "F0E6D2" },
  unlockedPassive: { color: "FF8811", underline: true },
  scaleBonus: { color: "F0E6D2" },
  spellTag: { color: "DDDD77" },
  scaleArmor: { color: "F0BA57" },
  keywordMajor: { color: "DDDD77" },
  keyword: { color: "DDDD77" },
  attention: { color: "F0E6D2" },
  specialRules: { color: "F0E6D2" },
  scaleMR: { color: "4FDFFF" },
  totalValue: { color: "F0E6D2" },
  scaleLethality: { color: "F95F55" },
  armorPen: { color: "F95F55" },
  magicPen: { color: "CE69FF" },
  caution: { color: "F2E766" },
  danger: { color: "FF0000" },
  keywordCaution: { color: "F2E766" },
  statGood: { color: "44FF44" },
  aura: { color: "F0E6D2" },
  keywordCost: { color: "A09B8C", italic: true },
  flavorText: { color: "8E7030", italic: true },
  stats: { color: "99FF99" },
  tftActiveRank: { color: "EFEFEF" },
  tftInactiveRank: { color: "696969" },
  tftitemrules: { color: "888888", italic: true },
  questionMarkCircle: { color: "F0E6D2" },
  status: { color: "AD76C4" },
  shield: { color: "4DD0EB" },
  speed: { color: "FFFDC9" },
  toggle: { color: "ffffff" },
  recast: { color: "D67351" },
  statTracking: { color: "FF8522" },
  rarityMythic: { color: "FF8811" },
  tap: { color: "F0E6D2" },
  hold: { color: "F0E6D2" },
  evolve: { color: "BC3598" },
  magicDamage: { color: "0ACBE6" },
  physicalDamage: { color: "F26522" },
  trueDamage: { color: "CDFAFA" },
  healing: { color: "60E08F" },
  activeRank: { color: "F0E6D2" },
  inactiveRank: { color: "5A5955" },
  spellName: { color: "F0E6D2" },
  rarityLegendary: { color: "F0E6D2" },
  rarityGeneric: { color: "CCC4B3" },
  lifeSteal: { color: "CE1C42" },
  lifesteal: { color: "CE1C42" },
  omnivamp: { color: "CE1C42" },
  OnHit: { color: "F0E6D2" },
  conflictMessage: { color: "FF5243", italic: true },
  attackSpeed: { color: "FFE384" },
  silver: { color: "C2D0CC" },
  ornnBonus: { color: "FF6D18" },
  rarityEpic: { color: "F0E6D2" },
  rarityBasic: { color: "F0E6D2" },
  TFTShadowItemBonus: { color: "5AF0C8" },
  TFTShadowItemPenalty: { color: "FF4B14" },
  TFTRadiantItemBonus: { color: "F4DE1A" },
  tftstrong: { color: "ffffff", italic: true },
  TFTTrackerLabel: { color: "888888" },
  TFTKeyword: { color: "CDBE91" },
  TFTGuildActive: { color: "E8BE2C" },
  TFTGuildInactive: { color: "696969" },
  TFTbold: { color: "ffffff" },
  TFTBonus: { color: "FFE384" },
}

FORMATREGEXP = /<(\/?)(#{FORMATTING.keys.map { |k| Regexp.escape(k) }.join("|")}|li|[Cc]|[Cc][2]|[Cc][33]|[Gg][Rr]|[Ll][Hh]|[Oo]|[Ff][Nn]|[Bb][Rr]|[Ff][Ss]|[Ii]|[Bb]|[Rr]|[Pp][Gg]|[Pp][Oo][Gg]|[Uu]|[Ss]|[Ii][Cc][Oo][Nn]|[Ii][Mm][Gg]|[Aa][Cc]|[Aa][Rr]|[Aa][Ll]|[Oo][Uu][Tt][Ll][Nn]|[Oo][Uu][Tt][Ll][Nn][2])(\s*\=\s*([^>]*))?>/
